### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by gdimopoulos** [raeffs/docker-host#37]
Nice collection of services, thanks for sharing! I'm trying to replicate this but hen I run `docker-compose up -d` it says there is not docker-compose.yml file.

I have set up the env file and sourced it but it doesn't help.

**Comment by raeffs** [comment]
thanks for your interest :)

I split up the docker compose file into different stacks/files and unfortunately didn't update the readme yet.

you have to specify one of the files you want to use for docker compose, for example:

```
docker-compose -f stack.infrastructure.yml up -d
```

I hope that will help you get started.

I will update the readme as soon as I find time.

**Comment by raeffs** [comment]
oh, and you will also need to manually create a network and volumes for the containers. that's also not mentioned in the readme yet. there is a hint for the network part in the init-workspace.sh.

**Comment by gdimopoulos** [comment]
That solved it, thanks!
